### ISSUE TITLE
addition

### ISSUE THREAD

**Issue by zasarafljivac** [puraxa/JShomeworkTwo#1]
svaki treci od 99.

 99 je prvi.

**Comment by puraxa** [comment]
Zar nisam tako napisao? i u prvom izvrsenju je 99 i sabira se na rezultat, onda se poveca u sljedecem izvrsenju i sabira opet na rezultat sve dok je manje od 188.

**Comment by zasarafljivac** [comment]
Treci je 101 jer od 99 krece. 99 nije trebalo da bude ukljuceno,  ali ok vjerovatno nisam dobro objasnio. Ne moras popravljati.
